services:
  db:
    image: postgres:16
    container_name: django_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        python src/manage.py migrate &&
        python src/create_superuser.py &&
        python src/manage.py runserver 0.0.0.0:8000
      "

volumes:
  postgres_data:
