services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3

  db:
    image: postgres:16
    container_name: django_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-django_db}
      POSTGRES_USER: ${POSTGRES_USER:-django_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-django_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
