services:
  web:
    env_file:
      - .env
    command: >
      sh -c "
        python src/manage.py migrate &&
        python src/create_superuser.py &&
        python src/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./src:/app/src
